### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by AlecDusheck** [ephs/portal#1]
How do you wanna deploy this? I could setup an App Engine instance for this (Core-ng is hosted like that) or we could setup a reverse proxy on the VPS to host both this and the Core API.

**Comment by eduxstad** [comment]
Whatever you think is best. I have no opinion. Don't deploy yet, I have a few things I want to patch up (which I'll probably do over break)

**Comment by AlecDusheck** [comment]
I’ll just deploy it as a prerelease (something like portal.pre.ephs.club). It really doesn’t take much effort to push a new release to Google Cloud.

**Comment by eduxstad** [comment]
Ok, thanks.

**Comment by AlecDusheck** [comment]
Live on https://portal.ephs.club.
